/**
 * shared/constants/config.ts
 * Canonical DEFAULT_CONFIG — single source of truth for Desktop UI and Web UI settings.
 */

export const DEFAULT_CONFIG = {
  theme: 'dark',
  accentColor: '#10b981',
  systemTextColor: '#f8fafc',
  customBgStart: '#0f172a',
  customBgEnd: '#1e1b4b',
  customPanelBg: '#1e293b',
  glassBlur: 'blur(16px)',
  fontFamily: "'Outfit', sans-serif",
  fontSize: '18px',
  apiKey: '',
  aiProvider: 'gemini',
  geminiModel: 'gemini-2.5-flash' as string,
  openaiModel: 'gpt-5.6-luna' as string,
  openrouterModel: 'openai/gpt-5.6-terra' as string,
  deepseekModel: 'deepseek-v4-flash' as string,
  anthropicModel: 'claude-sonnet-5' as string,
  ollamaModel: 'llama3:latest' as string,
  language: 'th-TH',
  proactiveInterval: 60,
  proactiveCooldown: 120,
  enableVoiceReply: true,
  enableCustomWorkflows: true,
  enableAgentCollaboration: false,
  ttsProvider: 'google',
  ttsVolume: 1.0,
  ttsSpeed: 1.0,
  ttsPitch: 1.0,
  pluginSpotifyEnabled: true,
  pluginCalendarEnabled: false,
  pluginGmailEnabled: false,
  pluginNotionEnabled: false,
  pluginDiscordEnabled: false,
  showDesktopWidget: true,
  mcpServers: {} as Record<string, any>,
  hfModel: 'Qwen/Qwen3.6-27B' as string,
  localApiBaseUrl: '',
  localModelName: 'local-model' as string,
  ollamaHost: '',
  anthropicApiKey: '',
  openaiApiKey: '',
  openrouterApiKey: '',
  deepseekApiKey: '',
  hfApiKey: '',
  bflApiKey: '',
  bflModel: 'flux-pro-1.1',
  automationBrowser: 'chromium',
  browserDebugUrl: 'http://127.0.0.1:9222/json/list',
  browserExtensionContextUrl: 'http://127.0.0.1:3212/context',
  enableHeadlessTaskQueue: false,
  enableAutoUpdate: false,
  updaterEndpoint: '',
  updaterPublicKey: '',
  telegramBotToken: '',
  enableTelegramBridge: false,
  discordBotToken: '',
  discordApplicationId: '',
  enableDiscordBridge: false,
  slackBotToken: '',
  slackAppToken: '',
  enableSlackBridge: false,
  lineChannelAccessToken: '',
  lineChannelSecret: '',
  enableLineBridge: false,
  lineWebhookHost: '127.0.0.1',
  lineWebhookPort: 3000,
  whatsappCloudAccessToken: '',
  whatsappPhoneNumberId: '',
  whatsappVerifyToken: '',
  whatsappAppSecret: '',
  enableWhatsappBridge: false,
  whatsappWebhookHost: '127.0.0.1',
  whatsappWebhookPort: 3001,
  enableBridgeAckNotification: true,
  bridgeAckMessage: '[Mint Agent] Remote command received, processing...',
  notionApiKey: '',
  notionDatabaseId: '',
  gmailClientId: '',
  gmailClientSecret: '',
  spotifyClientId: '',
  spotifyClientSecret: '',
  googleCalendarClientId: '',
  googleCalendarClientSecret: '',

  // Search Engine Settings
  searchProvider: 'google' as string,
  braveSearchApiKey: '',
  googleSearchApiKey: '',
  googleSearchCx: '',
  
  // Image Generation Settings
  imageGenProvider: 'gemini' as 'gemini' | 'dalle' | 'stability' | 'ideogram' | 'replicate' | 'bfl',
  stabilityApiKey: '',
  ideogramApiKey: '',
  replicateApiKey: '',

  // Video Generation Settings
  videoGenProvider: 'veo' as 'veo',
  veoModel: 'veo-3.1-generate-preview' as string,

  // Multi-Agent Configuration
  agents: [
    {
      id: 'planner',
      name: 'Planner',
      provider: 'gemini',
      model: 'gemini-2.5-flash',
      apiKey: '',
      systemPrompt: 'You are the Lead Planning Agent. Break down user goals into clear executable steps.',
      systemInstruction: 'You are the Lead Planning Agent. Break down user goals into clear executable steps.',
      enabled: true,
      avatar: '🎯',
    },
    {
      id: 'coder',
      name: 'Coder',
      provider: 'openai',
      model: 'gpt-5.6-luna',
      apiKey: '',
      systemPrompt: 'You are the Senior Software Engineer. Implement features with clean code and tests.',
      systemInstruction: 'You are the Senior Software Engineer. Implement features with clean code and tests.',
      enabled: true,
      avatar: '💻',
    },
    {
      id: 'critic',
      name: 'Critic',
      provider: 'anthropic',
      model: 'claude-sonnet-5',
      apiKey: '',
      systemPrompt: 'You are the Security & Quality Auditor. Review code, find bugs, and suggest improvements.',
      systemInstruction: 'You are the Security & Quality Auditor. Review code, find bugs, and suggest improvements.',
      enabled: true,
      avatar: '🔍',
    },
  ],

  // Custom AI Providers
  customProviders: [] as any[],

  // Custom Model Selections per Provider
  customModelSelections: {} as Record<string, string>,
}
